---
title: "fire risk grid"
output: html_notebook
---
# 概述
處理火燒資料，將火燒範圍網格化，利用相同網格萃取相關火燒風險因子，最後投入random forest regression建模，以了解各項因子對火燒風險之影響。
# 0. package
```{r}
library(data.table)
library(tidyverse)
library(sf)
library(parallel)
library(raster)
library(exactextractr) 
library(SPEI)
library(randomForest)

p_path <- "G:/我的雲端硬碟/協助分析/又綾/國家公園火燒風險評估/"
```

# 1. creating grid
```{r}
fire_rg <- st_read(paste0(p_path,"rawdata/layer/fire_merge4.shp"))
fire_rg <- fire_rg[,c("fid","firecode")]
### 製作基礎網格
st_bbox(fire_rg)
bs_grid <- st_bbox(c(xmin = 228700, ymin = 2569300,
                     xmax = 300900, ymax = 2713000), 
                   crs = st_crs(3826)) %>%
  st_as_sfc() %>%
  st_make_grid(., cellsize = c(100, 100), what = "polygons")
bs_grid_sf <-st_sf(geometry = bs_grid) 
rm(bs_grid)
### 擷取火燒範圍
fire_grid <- st_join(bs_grid_sf,fire_rg)
fire_grid <- fire_grid[!is.na(fire_grid$fid),]
st_write(fire_grid,paste0(p_path,"rawdata/fire_region_grid.shp"))
```
# 2. 處理veg ind
以火燒時間擷取NDVI, NBR以及NDMI數值。
NDVI與NDMI取前一年資料，作為火燒前背景。
NBR火燒前一年與火燒後一年差值，作為火燒嚴重數值。
```{r}
## 設立資料路徑
veg_rast_path <-paste0(p_path,"rawdata/layer/vegetation_index/")

## 篩選火燒網格id年分，並取出相關圖層
fire_grid$year <- substr(fire_grid$firecode,1,4)
fire_grid <- fire_grid[fire_grid$year>1986,]

fire_g2 <- lapply(unique(fire_grid$year),function(year){
  test <- fire_grid[fire_grid$year==year,]
  test_rast_pre <- stack(paste0(veg_rast_path,"nbr_mean_",as.numeric(year)-1,
                                ".tif"))
  test_rast_aft <- stack(paste0(veg_rast_path,"nbr_mean_",as.numeric(year)+1,
                                ".tif"))
  test$nbr_pre <- exact_extract(test_rast_pre[[1]],test, fun = "mean")
  test$ndvi <- exact_extract(test_rast_pre[[2]],test, fun = "mean")
  test$ndmi <- exact_extract(test_rast_pre[[3]],test, fun = "mean")
  test$nbr_aft <- exact_extract(test_rast_aft[[1]],test, fun = "mean")
  test$dnbr <- (test$nbr_pre-test$nbr_aft)*1000
  return(test)
})
plot(fire_g2)
st_write(fire_g2, paste0(p_path,"result/dnbr_grid.shp"))
fire_g2 <- do.call("rbind", fire_g2)
fire_g2$id <- paste0("n_",1:nrow(fire_g2))
fire_gp <- st_centroid(fire_g2)

write.csv(fire_gp,paste0(p_path,"result/grid_point.csv"))
```

# 3. ERA5_data deal
利用逐年的ERA5圖層，計算spei指標
該圖層一年一張，內有兩個波段，分別為降雨與潛在蒸散量。
```{r}
## test
ts_layer <- raster(paste0(p_path,"rawdata/layer/ERA5/ERA5_1951-0000000000-0000000000.tif"))

ts_dt <- raster::extract(ts_layer,fire_gp) %>% as.data.table()
ts_dt <- data.table(fire_gp[,c("id")],ts_dt)
colnames(ts_dt)[3] <- "var"
ts_dt[,grp:=.GRP,by=var]
bs_dt <- ts_dt[!duplicated(grp)]

write.csv(bs_dt,paste0(p_path,"/result/spei_point.csv"))
rm(ts_layer,test)
### 處理雲端下來的資test### 處理雲端下來的資料
spei <- fread(paste0(p_path,"rawdata/NP_fire_monthly_1950_2023_12_31.csv"))
spei[,grp:=bs_dt$grp]
spei[,`system:index`:=NULL][,.geo:=NULL][,id:=NULL]

spei_t <- melt(spei, id.vars=c("grp"),variable.name = "var",value.name="value")
spei_t[,year:=str_sub(var, start = 1, end = 4)][
  ,month:=str_sub(var,5,6)][
    ,var_name:=str_sub(var,8,str_count(var))
  ]
spei <- dcast(spei_t,year+month+grp~var_name,value.var = "value")

setnames(spei,c("potential_evaporation_sum",
              "total_precipitation_sum"),
         c("PE","precip"))
spei <- spei[!is.na(PE)][,V1:=NULL]

spei[,c("PE","precip"):=.(PE*1000,precip*1000)][
  ,D:=precip+PE]
for (i in unique(spei$grp)){
  spei[grp==i,spei_3:=as.data.table(spei(D,3)$fitted)][
        grp==i,spei_6:=as.data.table(spei(D,6)$fitted)][
         grp==i,spei_12:=as.data.table(spei(D,12)$fitted)][
           grp==i,spei_24:=as.data.table(spei(D,24)$fitted)]
}
### 合併資料
ts_dt <- as.data.table(ts_dt)
ts_dt[,geometry:=NULL][,var:=NULL]
fire_gdt <- as.data.table(fire_g2)
fire_gdt <- fire_gdt[ts_dt,on=.(id)]
fire_gdt[,month:=str_sub(firecode,5,6)]
colnames(spei)
fire_gdt <- spei[,.(year,month,grp,spei_3,spei_6,spei_12,spei_24)][
  fire_gdt,on=.(year,month,grp)]
rm(spei_t,spei)
```
# 4. single raster factor
處理坡度、坡向、TWI指數
```{r}

s_rf_path <- list.files(paste0(p_path,"/rawdata/layer/raster_factor/"),
                        full.names = TRUE)

rf_layer <- lapply(s_rf_path,raster)
fire_gdt$asp_recl <- exact_extract(rf_layer[[1]],fire_grid, fun = "mean")
fire_gdt$slope <- exact_extract(rf_layer[[2]],fire_grid, fun = "mean")
fire_gdt$twi <- exact_extract(rf_layer[[3]],fire_grid, fun = "mean")
rm(rf_layer)
```
# 5. human impact factor
處理山屋、山徑以及道路三項因子
```{r}
### 山屋
hf_str <- st_read(paste0(p_path,"rawdata/layer/vector_factor/山屋_FINAL2.shp"))
hf_str_j <-st_intersection(fire_g2[,c("id")],hf_str,left = TRUE) 
hf_str_j <- hf_str_j[!is.na(hf_str_j$fid),]
hf_str_j$area <-st_area(hf_str_j) 
hf_str_j <- as.data.table(hf_str_j)
hf_str_j[,area:=as.numeric(area)]
hf_str_l <- hf_str_j[,.(h_str_level=sum(level*area)/10000),by=.(id)]

fire_gdt <- hf_str_l[fire_gdt,on=.(id)]
fire_gdt[is.na(h_str_level),h_str_level:=0]
#### 修正風險等級，應該是距離山屋越近，風險等級越高(1~4改成4~1)
fire_gdt[h_str_level>0,h_str_level:=5-h_str_level]
rm(hf_str,hf_str_j)
### 路徑
hf_hiking_r <- st_read(paste0(p_path,"rawdata/layer/vector_factor/路徑_final2.shp"))
hf_hr_j <-st_intersection(fire_g2[,c("id")],hf_hiking_r,left=TRUE) 
hf_hr_j <- hf_hr_j[!is.na(hf_hr_j$fid),]
hf_hr_j$area <- st_area(hf_hr_j) 
hf_hr_j <- as.data.table(hf_hr_j)
hf_hr_l <- hf_hr_j[,.(hf_hr_level=sum(level*area/sum(area))),by=.(id)]
hf_hr_l[,hf_hr_level:=as.numeric(hf_hr_level)]
fire_gdt <- hf_hr_l[fire_gdt,on=.(id)]
fire_gdt[is.na(hf_hr_level),hf_hr_level:=0]
#### 修正風險等級，應該是距離路越近，風險等級越高(1~4改成4~1)
fire_gdt[hf_hr_level>0,hf_hr_level:=5-hf_hr_level]
rm(hf_hr_j,hf_hiking_r)
### 省道
hf_road_r <- st_read(paste0(p_path,"rawdata/layer/vector_factor/省道_final.gpkg"))
hf_ro_j <-st_intersection(fire_g2[,c("id")],hf_road_r,left=TRUE) 

hf_ro_j$area <- st_area(hf_ro_j) 
hf_ro_j <- as.data.table(hf_ro_j)
hf_ro_l <- hf_ro_j[,.(hf_ro_level=sum(level*area/sum(area))),by=.(id)]
hf_ro_l[,hf_ro_level:=as.numeric(hf_ro_level)]
fire_gdt <- hf_ro_l[fire_gdt,on=.(id)]
fire_gdt[is.na(hf_ro_level),hf_ro_level:=0]
rm(hf_ro_j,hf_road_r)
write.csv(fire_gdt,paste0(p_path,"result/fire_grid_and_all_factor.csv"))
```
# ramdon forest

```{r}
colnames(fire_gdt)
fire_gdt[is.na(twi)]
fire_gdt[,p_wi:=ndmi/ndvi]
fire_gdt_fire <- fire_gdt2[dnbr>0]
rf_mod_r <- randomForest(dnbr~hf_hr_level+hf_ro_level+h_str_level+spei_3+
                           spei_6+spei_12+spei_24+p_wi+asp_recl+
                           slope+twi+ndvi+ndmi,
                         data=fire_gdt,
                         mtry=4,
                         type= "regression",
                         na.action = na.omit,
                         ntree=200)
rf_mod_r
importance(rf_mod_r)
plot(rf_mod_r)
importance (rf_mod_r,type=1)
varImpPlot(rf_mod_r,type=1)
partialPlot(rf_mod_r,fire_gdt[!is.na(twi)],x.var = "twi")

## part II 將火燒變成有無
class(fire_gdt)
fire_gdt[,fir_fq:=NULL]
fire_gdt[dnbr<50,fir_fq:=0][dnbr>=50,fir_fq:=1]
fire_gdt[,fir_fq:=factor(fir_fq)][,spei_ins:=spei_3*spei_12]
rf_mod_r2 <- randomForest(fir_fq~hf_hr_level+hf_ro_level+h_str_level+spei_3+
                          spei_6+spei_12+spei_24+ndvi+asp_recl+
                          slope+twi+p_wi,
                          data=fire_gdt,
                          mtry=4,
                          ntree=1000,
                          type="classification",
                          na.action = na.omit)


rf_mod_r2
importance(rf_mod_r2)
plot(rf_mod_r2)
varImpPlot(rf_mod_r2)
partialPlot(rf_mod_r2,fire_gdt[!is.na(p_wi)],x.var = "p_wi")

```


